lab:
  children:
    lab_docker:
      hosts:
        lab-ns1: # rhel on proxmox
        lab-ns2: # debian on hyper-v
    lab_kubernetes:
      children:
        lab_k8s_cp:
          hosts:
            lab-cp1: # debian on hyper-v
            lab-cp2: # rocky on proxmox
            lab-cp3: # ubuntu on proxmox
        lab_k8s_worker:
          hosts:
            lab-worker1: # debian on hyper-v
        lab_etcd:
          hosts:
            lab-etcd1: # debian on hyper-v
            lab-etcd2: # debian on proxmox
            lab-etcd3: # oracle linux on proxmox

hlv3:
  children:
    docker:
      hosts:
    kubernetes:
      children:
        k8s_cp:
          hosts:
        k8s_worker:
          hosts:
        etcd:
          hosts:
